RUN_TUMBLE_LABEL = "RUN_TUMBLE_LABEL"
RUN_TUMBLE_INDEX = "RUN_TUMBLE_INDEX"
RUN_TUMBLE = "RUN_TUMBLE"
DISTANCE_TO_NEXT_POINT = "DISTANCE_TO_NEXT_POINT"
SPEED = "SPEED"

# Plotting constants
PLOT_SPEED_DISTRIBUTION = "PLOT_SPEED_DISTRIBUTION"
